-- MySQL Script generated by MySQL Workbench
-- Thu Apr  5 21:19:44 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema lab
-- -----------------------------------------------------
-- Manage labs.
DROP SCHEMA IF EXISTS `lab` ;

-- -----------------------------------------------------
-- Schema lab
--
-- Manage labs.
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lab` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `lab` ;

-- -----------------------------------------------------
-- Table `lab`.`teachers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lab`.`teachers` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `lab`.`teachers` (
  `number` INT NOT NULL AUTO_INCREMENT COMMENT 'auto increament.',
  `id` INT NOT NULL COMMENT 'Staff number.',
  `name` VARCHAR(45) NOT NULL,
  `logDate` DATETIME NOT NULL COMMENT 'The date this recode was added.',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
PACK_KEYS = Default;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `lab`.`courses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lab`.`courses` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `lab`.`courses` (
  `number` INT NOT NULL AUTO_INCREMENT,
  `courseID` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL COMMENT 'The name of course.',
  `studyTime` INT NOT NULL,
  `studyCridet` DECIMAL(1) NOT NULL,
  `logDate` DATETIME NOT NULL,
  PRIMARY KEY (`courseID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `lab`.`teacherCourse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lab`.`teacherCourse` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `lab`.`teacherCourse` (
  `number` INT NOT NULL AUTO_INCREMENT,
  `staffID` INT NOT NULL,
  `courseID` VARCHAR(45) NOT NULL,
  `logDate` DATETIME NOT NULL,
  PRIMARY KEY (`number`),
  CONSTRAINT `teacher`
    FOREIGN KEY (`staffID`)
    REFERENCES `lab`.`teachers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `course`
    FOREIGN KEY (`courseID`)
    REFERENCES `lab`.`courses` (`courseID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `stuffID_idx` ON `lab`.`teacherCourse` (`staffID` ASC);

SHOW WARNINGS;
CREATE INDEX `course_idx` ON `lab`.`teacherCourse` (`courseID` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `lab`.`timestamps`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lab`.`timestamps` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `lab`.`timestamps` (
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL);

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
